name = "Academic"
license = "MIT"
licenselink = "https://github.com/HugoBlox/theme-academic-cv/blob/main/LICENSE.md"
description = "Use the no-code website framework to easily build your site. Choose from 50+ widgets and deploy with one click! Fully personalize your site with themes, plugins, and language packs."
homepage = "https://github.com/HugoBlox/theme-academic-cv"
demosite = "https://hugoblox.com/templates/"
tags = [
  "widgets",
  "resume",
  "portfolio",
  "responsive",
  "clean",
  "personal",
  "company",
  "blog",
  "minimal",
  "light",
  "dark",
  "multilingual",
  "documentation",
  "landing page",
  "projects",
  "single page",
  "contact form",
  "mobile",
  "gallery",
  "search",
  "presentation",
  "simple",
  "minimalist",
  "starter",
  "modern",
  "one page",
  "customizable",
  "technical",
  "product",
  "slide",
]
features = [
  "page builder",
  "widgets",
  "themes",
  "search",
  "research publication system",
  "filterable portfolio",
  "blog",
  "create courses",
  "talks",
  "events",
  "slides",
  "gallery",
  "contact form",
]

[author]
name = "Shunsuke Kitada"
homepage = "https://shunk031.me"

# If porting an existing theme
[original]
name = "George Cushen"
homepage = "https://georgecushen.com"
repo = "https://github.com/wowchemy/starter-hugo-academic"
