# ref. Configuration File | Docs https://lychee.cli.rs/guides/config/

# Website timeout from connect to response finished.
timeout = 30

# Minimum wait time in seconds between retries of failed requests.
retry_wait_time = 10

# Comma-separated list of accepted status codes for valid links.
accept = ["100..=103", "200..=299", "302"]
