name: Check Broken Links

on:
  workflow_run:
    workflows: ["Page Build"]
    types:
      - completed

jobs:
  check-broken-links:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the lychee config file
      - uses: actions/checkout@v6

      - name: Download Build Artifact
        uses: actions/download-artifact@v6
        with:
          name: ${{ var.ARTIFACT_NAME }}
          path: ${{ var.ARTIFACT_PATH }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: "${{ var.ARTIFACT_PATH }} --config .lychee/config.toml"
